site_name: Chancellor Games API
site_url: https://chancellor.games
repo_url: https://github.com/chancellor-games/spec
repo_name: chancellor-games/spec
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    logo: fontawesome/solid/chess-king
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chancellor-games
      name: Chancellor Games on Github
    - icon: fontawesome/brands/docker
      link: https://github.com/orgs/chancellor-games/packages
      name: Chancellor Games Docker Images
markdown_extensions:
  # Python Markdown
  - smarty
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - API Spec:
      - spec/index.md
      - Glossary: spec/glossary.md
      - Objects:
          - Game: spec/objects/game.md
          - Player: spec/objects/player.md
          - State: spec/objects/state.md
          - Action: spec/objects/action.md
      - Messages:
          - Create/Created: spec/messages/creation.md
          - Setup: spec/messages/setup.md
          - Connected: spec/messages/connected.md
          - Action: spec/messages/action.md
          - Random: spec/messages/random.md
      - Rest API:
          - Game: spec/rest/game.md
          - Log: spec/rest/log.md
          - State: spec/rest/state.md
          - Actions: spec/rest/actions.md
  - Examples:
      - examples/index.md
      - Game Creation: examples/creation.md
      - Connecting: examples/connecting.md
      - Setup: examples/setup.md
      - Turns:
          - Ada: examples/ada.md
          - Betty: examples/better.md
          - Carol: examples/carol.md
  - Implementations:
      - implementations/index.md
      - Javascript:
          - Nomad: implementations/nomad.md
