[[redirects]]
  from = "/*"
  to = "/chancellor.json"
  status = 200

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/schema+json"
